//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTour
    {
        public LoaiTour()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int Id { get; set; }
        public string MaLoaiTour { get; set; }
        public string TenLoaiTour { get; set; }
    
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
