//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourDBEntities : DbContext
    {
        public TourDBEntities()
            : base("name=TourDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DanhSachDiemThamQuan> DanhSachDiemThamQuans { get; set; }
        public DbSet<DiaDiem> DiaDiems { get; set; }
        public DbSet<GiaTour> GiaTours { get; set; }
        public DbSet<LoaiTour> LoaiTours { get; set; }
        public DbSet<Tour> Tours { get; set; }
    }
}
