//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.DanhSachDiemThamQuans = new HashSet<DanhSachDiemThamQuan>();
            this.GiaTours = new HashSet<GiaTour>();
        }
    
        public string MaTour { get; set; }
        public string TenTour { get; set; }
        public int Id { get; set; }
        public int LoaiTourId { get; set; }
        public Nullable<bool> LaTourTrongNuoc { get; set; }
    
        public virtual ICollection<DanhSachDiemThamQuan> DanhSachDiemThamQuans { get; set; }
        public virtual ICollection<GiaTour> GiaTours { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
    }
}
